import { Suspense } from "react";
import type { Metadata } from "next";
import { Cedarville_Cursive, Inter } from "next/font/google";

import { Analytics } from "@/components/analytics";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

const cedarvilleCursive = Cedarville_Cursive({
  variable: "--font-cedarville-cursive",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Phillip Zoghbi Official Site | Gamification Expert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { NEXT_PUBLIC_GA_ID } = process.env;

  if (!NEXT_PUBLIC_GA_ID) {
    throw new Error("NEXT_PUBLIC_GA_ID is not defined");
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${cedarvilleCursive.variable} antialiased`}
      >
        <div className="container flex min-h-svh flex-col selection:bg-gray-300 xl:max-w-5xl 2xl:max-w-5xl">
          <Header />
          {children}
          <Footer />
        </div>
        <Toaster />
      </body>
      <Suspense>
        <Analytics gaId={NEXT_PUBLIC_GA_ID} />
      </Suspense>
    </html>
  );
}
