import type { Metadata } from "next";
import { Cedarville_Cursive, Inter } from "next/font/google";

import Footer from "@/components/footer";
import Header from "@/components/header";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

const cedarvilleCursive = Cedarville_Cursive({
  variable: "--font-cedarville-cursive",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Phillip Zoghbi Official Site | Gamification Expert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${cedarvilleCursive.variable} antialiased selection:bg-gray-300`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
